apiVersion: v1
kind: ConfigMap
metadata:
  name: my-postgres-db-configmap
data:
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
  DB_HOST: "my-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-postgres-db-password
type: Opaque
data:
  DB_PASSWORD: Q1BaYWRaUFhvcQ==
